apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: playbook
  annotations:
    github.com/project-slug: edenlabllc/playbook
    backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: unknown
  owner: leads
